# Generated by Django 3.2.19 on 2023-06-08 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_category',
            fields=[
                ('Pcid', models.IntegerField(primary_key=True, serialize=False)),
                ('Pcname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Pid', models.IntegerField(primary_key=True, serialize=False)),
                ('Pname', models.CharField(max_length=100)),
                ('Pprice', models.IntegerField()),
                ('Pdate', models.DateField()),
                ('Pcolour', models.CharField(max_length=10)),
                ('Pcname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product_category')),
            ],
        ),
    ]
