# Generated by Django 3.2.19 on 2023-06-20 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Pcname',
            new_name='pcname',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Pdate',
            new_name='pdate',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Pid',
            new_name='pid',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Pname',
            new_name='pname',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Pprice',
            new_name='pprice',
        ),
        migrations.RenameField(
            model_name='product_category',
            old_name='Pcid',
            new_name='pcid',
        ),
        migrations.RenameField(
            model_name='product_category',
            old_name='Pcname',
            new_name='pcname',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Pcolour',
        ),
    ]
